import numpy as np

# konu -> theta index
TOPIC_INDEX = {
    "3. Parti Uygulama Yönetimi / Erişimi Bilgisi ":  0 ,
    "API Security Bilgisi":  1 ,
    "APT Yönetimi  -  APT saldırılarını tespit etmek ve önlemek için güvenlik izleme ve uyarı sistemlerini kullanma becerisi":  2 ,
    "APT Yönetimi  -  APT tespiti ve müdahale becerisi.":  3 ,
    "APT Yönetimi  -  APT'lere karşı koruma sağlamak için güvenlik politikaları ve prosedürleri oluşturma ve uygulama becerisi":  4 ,
    "APT Yönetimi  -  APT'lere karşı koruma sağlamak için kullanılan güvenlik çözümlerini anlama becerisi":  5 ,
    "APT Yönetimi  -  Gelişmiş kalıcı tehditlere karşı savunma stratejilerini belirleme yeteneği.":  6 ,
    "APT Yönetimi  -  Özellikle gelişmiş tehditler için kullanılan teknikleri ve taktikleri anlama becerisi":  7 ,
    "Altyapı ve Platform Bilgisi":  8 ,
    "Altyapı ve Topoloji Mimarisi Bilgisi":  9 ,
    "Analiz ve Raporlama Bilgisi":  10 ,
    "Bilgi Güvenliği Teknolojileri Bilgisi":  11 ,
    "Bilgi Güvenliği ve Siber Güvenlik Bilgisi":  12 ,
    "Bot Koruma Yönetimi  -  Bot ağlarına karşı koruma stratejilerini geliştirme yeteneği.":  13 ,
    "Bot Koruma Yönetimi  -  Bot saldırılarını tespit etmek ve önlemek için güvenlik izleme ve uyarı sistemlerini kullanma becerisi":  14 ,
    "Bot Koruma Yönetimi  -  Botlara karşı koruma sağlamak için güvenlik politikaları ve prosedürleri oluşturma ve uygulama becerisi":  15 ,
    "Bot Koruma Yönetimi  -  Botlara karşı koruma sağlamak için kullanılan güvenlik çözümlerini anlama becerisi":  16 ,
    "Bot Koruma Yönetimi  -  Botların nasıl çalıştığını anlama becerisi":  17 ,
    "Bot Koruma Yönetimi  -  Zararlı bot trafiğini tespit ve engelleme becerisi.":  18 ,
    "Cloud Security Bilgisi":  19 ,
    "Container Security Bilgisi":  20 ,
    "DDoS Koruma Yönetimi  -  DDoS koruma çözümlerini konfigüre etme yeteneği.":  21 ,
    "DDoS Koruma Yönetimi  -  DDoS saldırılarına karşı koruma sağlamak için güvenlik politikaları ve prosedürleri oluşturma ve uygulama becerisi":  22 ,
    "DDoS Koruma Yönetimi  -  DDoS saldırılarına karşı koruma sağlamak için kullanılan güvenlik çözümlerini anlama becerisi":  23 ,
    "DDoS Koruma Yönetimi  -  DDoS saldırılarını tespit etme ve önleme becerisi.":  24 ,
    "DDoS Koruma Yönetimi  -  DDoS saldırılarını tespit etmek ve önlemek için güvenlik izleme ve uyarı sistemlerini kullanma becerisi":  25 ,
    "DDoS Koruma Yönetimi  -  DDoS saldırılarının nasıl çalıştığını anlama becerisi":  26 ,
    "DNS Yönetimi  -  DNS güvenlik açıklarını tespit etme ve düzeltme becerisi.":  27 ,
    "DNS Yönetimi  -  DNS güvenliği konularında bilgi sahibi olma.":  28 ,
    "DNS Yönetimi  -  DNS güvenliğini sağlamak için güvenlik politikaları ve prosedürleri oluşturma ve uygulama becerisi":  29 ,
    "DNS Yönetimi  -  DNS güvenliğini sağlamak için kullanılan güvenlik çözümlerini anlama becerisi":  30 ,
    "DNS Yönetimi  -  DNS saldırılarını tespit etmek ve önlemek için güvenlik izleme ve uyarı sistemlerini kullanma becerisi":  31 ,
    "DNS Yönetimi  -  DNS'nin çalışma şeklini ve işlevlerini anlama becerisi":  32 ,
    "Denetim ve Uyum Bilgisi (ISO 27001 vb.)":  33 ,
    "Firewall Politika Yönetimi  -  Güvenlik duvarı loglarını analiz etme ve düzeltme becerisi.":  34 ,
    "Firewall Politika Yönetimi  -  Güvenlik duvarı politikalarını oluşturma ve uygulama yeteneği.":  35 ,
    "Firewall Yönetimi  -  Ağ erişim kontrollerini tanımlama ve uygulama becerisi":  36 ,
    "Firewall Yönetimi  -  Ağ güvenliği politikalarını ve prosedürlerini oluşturma ve uygulama becerisi":  37 ,
    "Firewall Yönetimi  -  Ağ güvenliği çözümlerinin etkinliğini değerlendirme becerisi":  38 ,
    "Firewall Yönetimi  -  Ağ güvenliği çözümlerinin performansını izleme ve analiz etme becerisi":  39 ,
    "Firewall Yönetimi  -  Ağ saldırılarını tespit etme ve önleme becerisi":  40 ,
    "Firewall Yönetimi  -  Ağ trafiğini analiz etme ve şüpheli aktiviteleri belirleme becerisi":  41 ,
    "Firewall Yönetimi  -  Ağdaki kimlik ve erişim yönetimini anlama becerisi":  42 ,
    "Firewall Yönetimi  -  Farklı firewall çözümlerini konfigüre etme ve yönetme becerisi.":  43 ,
    "Firewall Yönetimi  -  Farklı türdeki güvenlik duvarlarının özelliklerini ve yeteneklerini anlama becerisi":  44 ,
    "Firewall Yönetimi  -  Güvenlik duvarı etkinliğini değerlendirme becerisi":  45 ,
    "Firewall Yönetimi  -  Güvenlik duvarı kayıtlarını analiz etme ve şüpheli aktiviteleri belirleme becerisi":  46 ,
    "Firewall Yönetimi  -  Güvenlik duvarı kurallarını oluşturma, yönetme ve denetleme becerisi":  47 ,
    "Firewall Yönetimi  -  Güvenlik duvarı olaylarını soruşturma ve yanıt verme becerisi":  48 ,
    "Firewall Yönetimi  -  Güvenlik duvarı performansını izleme ve analiz etme becerisi":  49 ,
    "Firewall Yönetimi  -  Güvenlik politikalarını oluşturma ve uygulama yeteneği.":  50 ,
    "Genel Mimari Bilgisi":  51 ,
    "Güvenlik Cihazları Konfigürasyon Bilgisi":  52 ,
    "Güvenlik Denetim ve İzleme Ürünleri":  53 ,
    "Güvenlik Denetimi ve İzleme  -  Erişim güvenliği önlemlerinin etkinliğini denetleme yeteneği.":  54 ,
    "Güvenlik Denetimi ve İzleme  -  Güvenlik olaylarını sürekli izleme ve değerlendirme becerisi.":  55 ,
    "Güvenlik Değerlendirmesi ve Test Bilgisi":  56 ,
    "Güvenlik Donanım ve Yazılımı Bilgisi":  57 ,
    "Güvenlik Mimarisi Bilgisi":  58 ,
    "Güvenlik Platformları Bilgisi":  59 ,
    "Güvenlik Protokolleri Bilgisi":  60 ,
    "Güvenlik Senaryo Dizaynı Bilgisi":  61 ,
    "Güvenlik Sertifikası Yönetimi  -  SSL/TLS sertifikalarını yönetme ve güncelleme becerisi.":  62 ,
    "Güvenlik Sertifikası Yönetimi  -  Sertifika tabanlı güvenlik politikalarını uygulama yeteneği.":  63 ,
    "IP, MPLS ve Internet Teknolojileri Bilgisi":  64 ,
    "IPS Yönetimi  -  Ağdaki saldırıları tespit etme ve önleme yeteneği.":  65 ,
    "IPS Yönetimi  -  Farklı türdeki IPS (örneğin, imza tabanlı, davranışsal) özelliklerini ve yeteneklerini anlama becerisi":  66 ,
    "IPS Yönetimi  -  IPS cihazlarını yapılandırma ve güncelleme becerisi.":  67 ,
    "IPS Yönetimi  -  IPS etkinliğini değerlendirme becerisi":  68 ,
    "IPS Yönetimi  -  IPS kayıtlarını analiz etme ve şüpheli aktiviteleri belirleme becerisi":  69 ,
    "IPS Yönetimi  -  IPS kurallarını oluşturma, yönetme ve denetleme becerisi":  70 ,
    "IPS Yönetimi  -  IPS olaylarını soruşturma ve yanıt verme becerisi":  71 ,
    "IPS Yönetimi  -  IPS performansını izleme ve analiz etme becerisi":  72 ,
    "ISO 22301 Bilgisi":  73 ,
    "ITIL, SOX, COBIT, BTK, KVKK ve ISO27001 Standartları Bilgisi":  74 ,
    "Kimlik ve Erişim Yönetimi Bilgisi":  75 ,
    "Konfigürasyon Yönetimi Bilgisi":  76 ,
    "Linux İşletim Sistemleri":  77 ,
    "Loadbalancer Bilgisi":  78 ,
    "Microsoft Windows İşletim Sistemleri":  79 ,
    "Mobil Cihaz Güvenliği  -  Mobil cihaz güvenliği tehditlerini tespit etme ve önleme becerisi.":  80 ,
    "Mobil Cihaz Güvenliği  -  Mobil cihazlar üzerinde güvenlik politikalarını uygulama yeteneği.":  81 ,
    "Network - Ağ Altyapı Bilgisi":  82 ,
    "Network - Ağ Bakımı Bilgisi":  83 ,
    "Network - Ağ Güvenlik Teknolojileri":  84 ,
    "Network - Ağ Güvenliği Bilgisi":  85 ,
    "Network - Ağ Mimarisi Bilgisi":  86 ,
    "Network - Ağ Mimarisi Sanallaştırma Konsept Bilgisi (NFV)":  87 ,
    "Network - Ağ Performansı İyileştirme Araçları Bilgisi (Network CEM ,HELIX, Massive)":  88 ,
    "Network - Ağ Yapılandırması Bilgisi":  89 ,
    "Network - Data Şebekesindeki Cihazların ve Altyapılıların Bilgisi (Router, Switch, WLAN)":  90 ,
    "Proje Yönetim Bilgisi":  91 ,
    "Proxy Sistemleri Yönetimi  -  Farklı türdeki proxy sistemlerinin (örneğin, HTTP, FTP, DNS) özelliklerini ve yeteneklerini anlama becerisi":  92 ,
    "Proxy Sistemleri Yönetimi  -  Proxy sistem etkinliğini değerlendirme becerisi":  93 ,
    "Proxy Sistemleri Yönetimi  -  Proxy sistem kayıtlarını analiz etme ve şüpheli aktiviteleri belirleme becerisi":  94 ,
    "Proxy Sistemleri Yönetimi  -  Proxy sistem olaylarını soruşturma ve yanıt verme becerisi":  95 ,
    "Proxy Sistemleri Yönetimi  -  Proxy sistem performansını izleme ve analiz etme becerisi":  96 ,
    "Proxy Sistemleri Yönetimi  -  Proxy sistemlerini kurma, yapılandırma ve yönetme becerisi":  97 ,
    "Proxy Sistemleri Yönetimi  -  Proxy sunucularını konfigüre etme ve güncelleme becerisi.":  98 ,
    "Proxy Sistemleri Yönetimi  -  İnternet trafiğini filtreleme ve yönlendirme yeteneği.":  99 ,
    "Siber Kriz Yönetimi Bilgisi":  100 ,
    "Sistem Entegrasyonu ve Taşıma Bilgisi":  101 ,
    "Teknik Şartname Hazırlama Bilgisi":  102 ,
    "Uygulama Güvenliği Bilgisi":  103 ,
    "Uygulama Seviyesi Güvenlik  -  Uygulama tabanlı güvenlik açıklarını tespit etme ve düzeltme becerisi.":  104 ,
    "Uygulama Seviyesi Güvenlik  -  Uygulamaların güvenliğini değerlendirme ve iyileştirme yeteneği.":  105 ,
    "WAF Yönetimi  -  Farklı türdeki WAF (örneğin, statik, dinamik, içerik tabanlı) özelliklerini ve yeteneklerini anlama becerisi":  106 ,
    "WAF Yönetimi  -  WAF etkinliğini değerlendirme becerisi":  107 ,
    "WAF Yönetimi  -  WAF kayıtlarını analiz etme ve şüpheli aktiviteleri belirleme becerisi":  108 ,
    "WAF Yönetimi  -  WAF kurallarını oluşturma, yönetme ve denetleme becerisi":  109 ,
    "WAF Yönetimi  -  WAF olaylarını soruşturma ve yanıt verme becerisi":  110 ,
    "WAF Yönetimi  -  WAF performansını izleme ve analiz etme becerisi":  111 ,
    "WAF Yönetimi  -  WAF'ın konfigürasyonunu ve güncellemelerini yönetme becerisi.":  112 ,
    "WAF Yönetimi  -  Web uygulamalarını koruma stratejilerini belirleme yeteneği.":  113 ,
    "Zafiyet ve Uyumluluk Tarama Sistemleri":  114
}


def sigmoid(x):
    return 1 / (1 + np.exp(-x))


def p_3pl(theta, item):

    # Bu soru hangi ana konuya ait?
    k = TOPIC_INDEX[item.sub_topic]

    # 3PL olasılığı
    return item.c + (1 - item.c) * sigmoid(
        item.a * (theta[k] - item.b)
    )
